# -*- coding: utf-8 -*-
"""chat_bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJ2Bjdh0vy7V4aUo_oU00tEYhhFcijVi
"""

# chatbot_app.py
import sqlite3
import streamlit as st
from huggingface_hub import InferenceClient

st.title("🤖 AI Chatbot")
st.header("gpt-2 model use in chat bot")

api_key = st.text_input("Enter your Hugging Face API Key:", type="password")


user_input = st.text_input("Ask me anything:")

if user_input:
    if not api_key:
        st.error("⚠️ Please enter your API key first.")
    else:
        try:
            client = InferenceClient(token=api_key)

            response = client.text_generation(
                model="gpt2",
                prompt=user_input,
                max_new_tokens=50
            )

            st.success("Response:")
            st.write(response)

        except Exception as e:
            st.error("Something went wrong. Check your API key.")
            st.exception(e)

# database
conn = sqlite3.connect("chat_memory.db", check_same_thread=False)
c = conn.cursor()
#excute the database
c.execute("""
CREATE TABLE IF NOT EXISTS memory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT,
    bot TEXT
)
""")
#run and save database
conn.commit()


def chatbot(query: str) -> str:
    # Fetch previous conversation (last 5 messages)
    c.execute("SELECT user, bot FROM memory ORDER BY id DESC LIMIT 6")
    history = c.fetchall()
    prompt_history = ""
    for u, b in reversed(history):
        prompt_history += f"User: {u}\nBot: {b}\n"

    # Combine with current query
    final_prompt = prompt_history + f"User: {query}\nBot:"

    
    response = client.chat_completion(
        model="Qwen/Qwen2.5-7B-Instruct",
        messages=[{"role": "user", "content": final_prompt}]
    )

    answer = response.choices[0].message.content.strip()

    # Save current conversation to DB
    c.execute("INSERT INTO memory (user, bot) VALUES (?, ?)", (query, answer))
    conn.commit()

    return answer

