# -*- coding: utf-8 -*-
"""chat_bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJ2Bjdh0vy7V4aUo_oU00tEYhhFcijVi
"""

# chatbot_app.py
import sqlite3
import streamlit as st
from huggingface_hub import InferenceClient

try:
    api_key = st.text_input("Enter your Hugging Face API Key:", type="password")
except Exception as e:
    st.error(f"Error while taking API key input: {e}")
    api_key = None

client = InferenceClient(token=api_key)


# database
conn = sqlite3.connect("chat_memory.db", check_same_thread=False)
c = conn.cursor()
#excute the database
c.execute("""
CREATE TABLE IF NOT EXISTS memory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT,
    bot TEXT
)
""")
#run and save database
conn.commit()


def chatbot(query: str) -> str:
    # Fetch previous conversation (last 5 messages)
    c.execute("SELECT user, bot FROM memory ORDER BY id DESC LIMIT 6")
    history = c.fetchall()
    prompt_history = ""
    for u, b in reversed(history):
        prompt_history += f"User: {u}\nBot: {b}\n"

    # Combine with current query
    final_prompt = prompt_history + f"User: {query}\nBot:"

    # Call Hugging Face model
    response = client.chat_completion(
        model="Qwen/Qwen2.5-7B-Instruct",
        messages=[{"role": "user", "content": final_prompt}]
    )

    answer = response.choices[0].message.content.strip()

    # Save current conversation to DB
    c.execute("INSERT INTO memory (user, bot) VALUES (?, ?)", (query, answer))
    conn.commit()

    return answer

st.title("AI Job Assistant ")
user_input = st.text_input("Ask me anything ")

if user_input:
    answer = chatbot(user_input)
    st.write(answer)
